### ISSUE TITLE
Reading Mission Error: Prision.Island Elements.c

### ISSUE THREAD

**Issue by Peinful** [Wizbaggd/ButlerZ-Mission-Framework#1]
So i've been getting an issue with Mission compiles, I've attempted removing and editing files a bunch but nothing seems to be working currently.

![image](https://user-images.githubusercontent.com/23212709/48308543-81f87e00-e55f-11e8-95f8-dced6371b187.png)

**Comment by Wizbaggd** [comment]
yeah, this wasn't intended for others to use, you won't find support here for this, sorry
